### ISSUE TITLE
Why forcing ECS ?

### ISSUE THREAD

**Issue by RUSshy** [elnormous/ouzel#12]
Hello

Everywhere i see C++ game framework they force ECS, people don't seems to understand difference between Engine and Game Framework

I wish it was more like MonoGame or libGDX, a set of tools to make a game, not a motor that i can use to make my game :(

**Comment by agriic** [comment]
As i get it - your issue is incorrect naming - game framework not engine?

ECS is architecture choice and chosen often as it gives great flexibility.
Game framework goes with engine. Usually people want both because they want as fast as possible to create their idea.
Everything (low level) you want is there in source - it's not like source would be closed..

**Comment by elnormous** [comment]
Ouzel is a game engine, not a framework (scene editor, resource packer etc. are under development). The first version of Ouzel was using inheritance to implement different Node types, but the inheritance graph started to become too complex so I moved to ECS. Ouzel will not be libgdx or MonoGame. If you need a C/C++ framework, use SDL, GLFW or SFML.
