### ISSUE TITLE
Problem with handleKeyEvent(UINT msg, WPARAM wParam, LPARAM lParam)

### ISSUE THREAD

**Issue by Commondor** [elnormous/ouzel#28]
This function don't catch LeftAlt, RightAlt and LeftGUI (VK_LWIN) keys:

void handleKeyEvent(UINT msg, WPARAM wParam, LPARAM lParam);

For LeftGUI (VK_LWIN) key need append:

		case VK_LWIN:
			if ((lParam & 0x1000000) == 0)
				vKey = VK_LWIN;
			else
				vKey = VK_RWIN;
			break;

For LeftAlt, RightAlt keys need append:

	case WM_SYSKEYDOWN:
	case WM_SYSKEYUP:
	case WM_KEYDOWN:
	case WM_KEYUP:
        {
            handleKeyEvent(msg, wParam, lParam);
            break;
        }

**Comment by elnormous** [comment]
You don't have to check the lparam for VK_LWIN, because WV_LWIN and VK_RWIN are being sent correctly (you can test it yourself). You can also check the Microsoft's code: https://github.com/Microsoft/Windows-classic-samples/blob/master/Samples/IME/cpp/SampleIME/Globals.cpp#L334

I implemented the handling of the WM_SYSKEYDOWN and WM_SYSKEYUP. Thank you!
